"use client";
import { useCallback, useEffect, useState } from "react";
import { apiRequest, initializeCsrf } from "@/lib/api/client";
import { type Lead, type PageResponse, formatDate, labels } from "@/features/admin/types";
import { Heading, State } from "../dashboard/page";
const statuses=["NEW","VIEWED","IN_PROGRESS","PROPOSAL_SENT","CONVERTED","ARCHIVED"];
const services=["LANDING_PAGE","INSTITUTIONAL_SITE","CRM","WHATSAPP_CHATBOT","CUSTOM_SYSTEM","UNDECIDED"];
export default function LeadsPage(){const [result,setResult]=useState<PageResponse<Lead>>();const [selected,setSelected]=useState<Lead>();const [filters,setFilters]=useState({search:"",status:"",service:"",page:0});const [error,setError]=useState("");
 const load=useCallback(()=>{const q=new URLSearchParams({page:String(filters.page),size:"20",sort:"createdAt",direction:"desc"});if(filters.search)q.set("search",filters.search);if(filters.status)q.set("status",filters.status);if(filters.service)q.set("service",filters.service);apiRequest<PageResponse<Lead>>(`/api/v1/admin/leads?${q}`).then(setResult).catch(e=>setError(e.message))},[filters]);useEffect(load,[load]);
 async function open(id:string){try{setSelected(await apiRequest<Lead>(`/api/v1/admin/leads/${id}`));load()}catch(e){setError(e instanceof Error?e.message:"Falha ao abrir")}}
 async function patch(path:string,body?:unknown){if(!selected)return;try{await initializeCsrf();setSelected(await apiRequest<Lead>(`/api/v1/admin/leads/${selected.id}/${path}`,{method:"PATCH",body:body?JSON.stringify(body):undefined}));load()}catch(e){setError(e instanceof Error?e.message:"Falha ao atualizar")}}
 return <><Heading title="Contatos" text="Consulte e organize as solicitações recebidas pelo site."/><form className="admin-card mt-6 grid gap-4 md:grid-cols-4" onSubmit={e=>{e.preventDefault();setFilters({...filters,page:0})}}><div className="md:col-span-2"><label className="form-label" htmlFor="search">Nome, empresa ou e-mail</label><input className="form-input" id="search" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></div><div><label className="form-label" htmlFor="status">Status</label><select className="form-input" id="status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value,page:0})}><option value="">Todos</option>{statuses.map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></div><div><label className="form-label" htmlFor="service">Serviço</label><select className="form-input" id="service" value={filters.service} onChange={e=>setFilters({...filters,service:e.target.value,page:0})}><option value="">Todos</option>{services.map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></div><button className="admin-button md:col-span-4 md:justify-self-start">Pesquisar</button></form>
 {error&&<p className="mt-4 text-sm text-[var(--danger)]" role="alert">{error}</p>}{!result?<div className="mt-6"><State text="Carregando contatos..."/></div>:result.items.length===0?<div className="mt-6"><State text="Nenhum contato encontrado."/></div>:<div className="admin-card mt-6 overflow-x-auto p-0"><table className="w-full min-w-3xl text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Contato</th><th className="p-4">Serviço</th><th className="p-4">Status</th><th className="p-4">Recebido</th><th className="p-4">Ação</th></tr></thead><tbody className="divide-y divide-slate-100">{result.items.map(l=><tr key={l.id}><td className="p-4"><strong>{l.name}</strong><br/><span className="text-slate-500">{l.company||l.email}</span></td><td className="p-4">{labels[l.serviceInterest]}</td><td className="p-4">{labels[l.status]}</td><td className="p-4">{formatDate(l.createdAt)}</td><td className="p-4"><button className="admin-link" onClick={()=>open(l.id)}>Detalhes</button></td></tr>)}</tbody></table></div>}
 {result&&result.totalPages>1&&<div className="mt-4 flex items-center justify-between text-sm"><button disabled={result.page===0} onClick={()=>setFilters({...filters,page:filters.page-1})}>← Anterior</button><span>Página {result.page+1} de {result.totalPages}</span><button disabled={result.page+1>=result.totalPages} onClick={()=>setFilters({...filters,page:filters.page+1})}>Próxima →</button></div>}
 {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/35" onMouseDown={e=>e.target===e.currentTarget&&setSelected(undefined)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl" aria-label="Detalhes do contato"><div className="flex justify-between"><h2 className="text-2xl font-bold">{selected.name}</h2><button onClick={()=>setSelected(undefined)} aria-label="Fechar">✕</button></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><Detail label="Empresa" value={selected.company||"—"}/><Detail label="E-mail" value={selected.email}/><Detail label="Telefone" value={selected.phone}/><Detail label="Serviço" value={labels[selected.serviceInterest]}/><Detail label="Orçamento" value={labels[selected.budgetRange]}/><Detail label="Origem" value={selected.source}/><Detail label="Consentimento" value={selected.privacyConsent?`Registrado em ${formatDate(selected.consentDate)}`:"Não"}/><Detail label="E-mails" value={`Notificação: ${selected.notificationStatus}; confirmação: ${selected.confirmationStatus}`}/></dl><div className="mt-6"><p className="form-label">Mensagem</p><p className="rounded-xl bg-slate-50 p-4 text-sm whitespace-pre-wrap">{selected.message}</p></div><div className="mt-6"><label className="form-label" htmlFor="lead-status">Status</label><select className="form-input" id="lead-status" value={selected.status} onChange={e=>patch("status",{status:e.target.value})}>{statuses.map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></div><div className="mt-5"><label className="form-label" htmlFor="notes">Observação interna</label><textarea className="form-input min-h-28" id="notes" maxLength={4000} value={selected.internalNotes??""} onChange={e=>setSelected({...selected,internalNotes:e.target.value})}/><button className="admin-button mt-2" onClick={()=>patch("notes",{notes:selected.internalNotes})}>Salvar observação</button></div><button className="mt-8 text-sm font-bold text-[var(--danger)]" disabled={selected.status==="ARCHIVED"} onClick={()=>confirm("Arquivar este contato?")&&patch("archive")}>Arquivar contato</button></aside></div>}</>}
function Detail({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-bold uppercase text-slate-400">{label}</dt><dd className="mt-1 break-words text-slate-700">{value}</dd></div>}
