"use client";
import { useEffect, useMemo, useState } from "react";
import { apiRequest, initializeCsrf } from "@/lib/api/client";
import type { SectionDetail, Version } from "./types";

type Leaf={path:(string|number)[];label:string;value:string;editable:boolean};
const fixed=new Set(["icon","href","number","locale"]);
function leaves(node:unknown,path:(string|number)[]=[]):Leaf[]{if(typeof node==="string"){const key=String(path.at(-1));return [{path,label:path.map(String).join(" › "),value:node,editable:!fixed.has(key)}]};if(Array.isArray(node))return node.flatMap((v,i)=>leaves(v,[...path,i]));if(node&&typeof node==="object")return Object.entries(node).flatMap(([k,v])=>leaves(v,[...path,k]));return []}
function update(node:Record<string,unknown>,path:(string|number)[],value:string){const copy=structuredClone(node);let current:unknown=copy;for(let i=0;i<path.length-1;i++)current=(current as Record<string|number,unknown>)[path[i]]; (current as Record<string|number,unknown>)[path.at(-1)!]=value;return copy}
export function ContentEditor({sectionKey}:{sectionKey:string}){const [data,setData]=useState<SectionDetail>();const [versions,setVersions]=useState<Version[]>([]);const [content,setContent]=useState<Record<string,unknown>>({});const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 async function load(){const [detail,history]=await Promise.all([apiRequest<SectionDetail>(`/api/v1/admin/content/${sectionKey}`),apiRequest<Version[]>(`/api/v1/admin/content/${sectionKey}/versions`)]);setData(detail);setVersions(history);setContent(structuredClone(detail.draft?.contentData??detail.published?.contentData??{}));}
 useEffect(()=>{void Promise.all([apiRequest<SectionDetail>(`/api/v1/admin/content/${sectionKey}`),apiRequest<Version[]>(`/api/v1/admin/content/${sectionKey}/versions`)]).then(([detail,history])=>{setData(detail);setVersions(history);setContent(structuredClone(detail.draft?.contentData??detail.published?.contentData??{}));}).catch(e=>setMessage(e.message));},[sectionKey]);const fields=useMemo(()=>leaves(content),[content]);
 async function action(fn:()=>Promise<unknown>,success:string){setBusy(true);setMessage("");try{await initializeCsrf();await fn();setMessage(success);await load();}catch(e){setMessage(e instanceof Error?e.message:"A operação falhou.");}finally{setBusy(false)}}
 if(!data)return <div className="admin-card" role="status">{message||"Carregando editor..."}</div>;
 return <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section className="admin-card"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">{data.section.title}</h1><p className="mt-1 text-sm text-slate-500">{fields.filter(f=>f.editable).length} campos textuais</p></div><div className="flex gap-2"><button className="admin-button admin-button-secondary" disabled={busy} onClick={()=>action(()=>apiRequest(`/api/v1/admin/content/${sectionKey}`,{method:"PUT",body:JSON.stringify({contentData:content})}),"Rascunho salvo.")}>Salvar rascunho</button><button className="admin-button" disabled={busy||!data.draft} onClick={()=>confirm("Publicar este rascunho no site?")&&action(()=>apiRequest(`/api/v1/admin/content/${sectionKey}/publish`,{method:"POST"}),"Conteúdo publicado.")}>Publicar</button></div></div>{message&&<p className="mt-4 rounded-lg bg-slate-50 p-3 text-sm" role="status">{message}</p>}<div className="mt-6 space-y-5">{fields.filter(f=>f.editable).map(field=><div key={field.label}><div className="flex justify-between"><label className="form-label" htmlFor={field.label}>{field.label}</label><span className="text-xs text-slate-500">{field.value.length}/4000</span></div>{field.value.length>100?<textarea className="form-input min-h-28" id={field.label} maxLength={4000} value={field.value} onChange={e=>setContent(update(content,field.path,e.target.value))}/>:<input className="form-input" id={field.label} maxLength={4000} value={field.value} onChange={e=>setContent(update(content,field.path,e.target.value))}/>}</div>)}</div></section>
 <aside className="space-y-6"><section className="admin-card xl:sticky xl:top-6"><h2 className="font-bold">Prévia dos textos</h2><div className="mt-4 max-h-[55vh] space-y-3 overflow-auto rounded-xl bg-slate-50 p-4">{fields.filter(f=>f.editable).map(f=><div key={f.label}><p className="text-[.65rem] font-bold uppercase tracking-wider text-slate-400">{f.label}</p><p className="mt-1 text-sm text-slate-700">{f.value}</p></div>)}</div></section><section className="admin-card"><h2 className="font-bold">Versões</h2><div className="mt-4 space-y-3">{versions.map(v=><div className="flex items-center justify-between gap-3 text-sm" key={v.id}><span>v{v.versionNumber} · {v.status}</span><button className="admin-link disabled:opacity-40" disabled={busy} onClick={()=>confirm(`Restaurar a versão ${v.versionNumber} como novo rascunho?`)&&action(()=>apiRequest(`/api/v1/admin/content/${sectionKey}/restore/${v.id}`,{method:"POST"}),"Versão restaurada como rascunho.")}>Restaurar</button></div>)}</div></section></aside></div>}
